### ISSUE TITLE
token获取问题

### ISSUE THREAD

**Issue by JonahLee1999** [moeshin/hzj-sign#1]
您好。在 会话存储空间中没有token 值，在cookie中找到的token值调用后，报错如下
<http.client.HTTPResponse object at 0x00000227CB6CC610>
签到失败：500 Internal Server Error
{"timestamp":1644757177644,"status":500,"error":"Internal Server Error","exception":"java.lang.NumberFormatException","message":"For input string: \"NZ\"","path":"/sign/addSignIn"}

**Comment by moeshin** [comment]
这不能确定是不是 token 的问题。
配置中有一个值是 NZ 吗？

**Comment by JonahLee1999** [comment]
> 这不能确定是不是 token 的问题。 配置中有一个值是 NZ 吗？

从cookie中拿到的token值中含有NZ两个字母，但是这俩字母不是打头也不是结尾，而是中间的俩字母，更换token后，仍然报错：
<http.client.HTTPResponse object at 0x0000027A60D4C7F0>
签到失败：500 Internal Server Error
{"timestamp":1644763428418,"status":500,"error":"Internal Server Error","exception":"java.lang.NumberFormatException","message":"For input string: \"Dv\"","path":"/sign/addSignIn"}

此时token为 A2DvVvWWN35LUlXsL.........

辛苦老哥了👍👍👍

**Comment by moeshin** [comment]
也许学校不一样可能点小差异。
或者你用用这个老哥写的，他直接账号密码登录的 https://github.com/fffovo/hzj_AutoSignIn

**Comment by JonahLee1999** [comment]
好的，谢谢老哥
