### ISSUE TITLE
API

### ISSUE THREAD

**Issue by cc0817** [moeshin/hzj-sign#2]
现在这个接口是不是改了 都是vue

**Comment by cc0817** [comment]
{"token":"*****gA=","trip":false,"address":"","location":"","pushplus":""}
json我是这样写的

**Comment by moeshin** [comment]
毕业后账号全部被学校注销掉了，不知道啥情况了

**Comment by moeshin** [comment]
3801b90d86b078d3310cddfa89f7d6afa8b728ff
